/*
 * TEST of GIT pushing
 */
package Main;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.*;
import static javax.swing.SwingConstants.CENTER;

/**
 *
 * @author Lachtara
 */
public class Infinitum extends javax.swing.JFrame {

	/**
	 * Creates new form Infinitum
	 */
	public Infinitum() {
//		this.setUndecorated(rootPaneCheckingEnabled);
		initComponents();
		// set view options
		setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
		setExtendedState(JFrame.MAXIMIZED_BOTH);
		// set background
//		getContentPane().setBackground(Color.black);
		ImageIcon logo = new ImageIcon("D:\\WorkspaceNetbeans\\Infinitum\\src\\Main\\Infinitum_Dark_800x640.jpg");
		lblLogo.setIcon(logo);
		lblLogo.setHorizontalAlignment(CENTER);
		lblLogo.setBackground(Color.BLACK);
//		setContentPane(lblLogo);
		// set 
		pnlMain.setBackground(Color.WHITE);
		layPnlMain.setLayer(lblLogo, 0);
		layPnlMain.setLayer(pnlMain, 1);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layPnlMain = new javax.swing.JLayeredPane();
        pnlMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlMenuButtons = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Infinitum");

        pnlMain.setOpaque(false);

        pnlMenu.setOpaque(false);
        pnlMenu.setLayout(new java.awt.GridBagLayout());

        pnlMenuButtons.setOpaque(false);
        pnlMenuButtons.setPreferredSize(new java.awt.Dimension(255, 470));
        pnlMenuButtons.setLayout(new java.awt.GridLayout(5, 1, 0, 10));

        jButton1.setText("jButton1");
        pnlMenuButtons.add(jButton1);

        jButton2.setText("jButton2");
        pnlMenuButtons.add(jButton2);

        jButton3.setText("jButton3");
        pnlMenuButtons.add(jButton3);

        jButton4.setText("jButton4");
        pnlMenuButtons.add(jButton4);

        jButton5.setText("jButton5");
        pnlMenuButtons.add(jButton5);

        pnlMenu.add(pnlMenuButtons, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(665, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblLogo.setBackground(new java.awt.Color(0, 0, 0));
        lblLogo.setMaximumSize(new java.awt.Dimension(2, 2));
        lblLogo.setMinimumSize(new java.awt.Dimension(2, 2));
        lblLogo.setOpaque(true);
        lblLogo.setPreferredSize(new java.awt.Dimension(2, 2));

        layPnlMain.setLayer(pnlMain, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layPnlMain.setLayer(lblLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layPnlMainLayout = new javax.swing.GroupLayout(layPnlMain);
        layPnlMain.setLayout(layPnlMainLayout);
        layPnlMainLayout.setHorizontalGroup(
            layPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE))
        );
        layPnlMainLayout.setVerticalGroup(
            layPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layPnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layPnlMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layPnlMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Infinitum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Infinitum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Infinitum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Infinitum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
        //-- prevents the gui from looking different depending on OS
		setDefaultLookAndFeelDecorated(true);
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Infinitum().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLayeredPane layPnlMain;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMenuButtons;
    // End of variables declaration//GEN-END:variables
}
