/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.ResultSet;
/**
 *
 * @author lachtara
 */
public class PanelCharacterTile extends javax.swing.JPanel {
	
	protected int ID;
	
	/**
	 * Creates new form PanelCharacterTile
	 */
	public PanelCharacterTile() {
		initComponents();
	}
	
	// getter and setter
	public void setLblCharname (String text) {
		lblCharname.setText(text);
	}
	
	public String getLblCharname () {
		return lblCharname.getText();
	}
	
	public void setLblRealname (String text) {
		lblRealname.setText(text);
	}
	
	public String getLblRealname () {
		return lblRealname.getText();
	}
	
	public void setActiveSelected (boolean state) {
		btnTglActive.setSelected(state);
		if (state) {
			btnTglActive.setText("deactivate");
		} else {
			btnTglActive.setText("activate");
		}
	}
	
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTileHead = new javax.swing.JPanel();
        lblCharname = new javax.swing.JLabel();
        lblRealname = new javax.swing.JLabel();
        btnTglActive = new javax.swing.JToggleButton();
        pnlTileInfo = new javax.swing.JPanel();
        lblAttack = new javax.swing.JLabel();
        lblDefense = new javax.swing.JLabel();
        lblAttackVal = new javax.swing.JLabel();
        lblDefenseVal = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.black));
        setPreferredSize(new java.awt.Dimension(400, 200));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        lblCharname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCharname.setText("Charname");
        lblCharname.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblCharname.setMaximumSize(null);

        lblRealname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRealname.setText("Realname");
        lblRealname.setMaximumSize(null);

        btnTglActive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTglActiveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTileHeadLayout = new javax.swing.GroupLayout(pnlTileHead);
        pnlTileHead.setLayout(pnlTileHeadLayout);
        pnlTileHeadLayout.setHorizontalGroup(
            pnlTileHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTileHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTileHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTileHeadLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblRealname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlTileHeadLayout.createSequentialGroup()
                        .addComponent(lblCharname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                        .addComponent(btnTglActive)
                        .addContainerGap())))
        );
        pnlTileHeadLayout.setVerticalGroup(
            pnlTileHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTileHeadLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnlTileHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCharname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTglActive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRealname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(pnlTileHead, gridBagConstraints);

        lblAttack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAttack.setText("Angriff");
        lblAttack.setMaximumSize(null);

        lblDefense.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDefense.setText("Verteidigung");
        lblDefense.setMaximumSize(null);

        lblAttackVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAttackVal.setText("5");
        lblAttackVal.setMaximumSize(null);

        lblDefenseVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDefenseVal.setText("3");
        lblDefenseVal.setMaximumSize(null);

        javax.swing.GroupLayout pnlTileInfoLayout = new javax.swing.GroupLayout(pnlTileInfo);
        pnlTileInfo.setLayout(pnlTileInfoLayout);
        pnlTileInfoLayout.setHorizontalGroup(
            pnlTileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTileInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDefense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(pnlTileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDefenseVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAttackVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );
        pnlTileInfoLayout.setVerticalGroup(
            pnlTileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTileInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAttackVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTileInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDefense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDefenseVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        add(pnlTileInfo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTglActiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTglActiveMouseClicked
        ResultSet result = DB.getAll();
		try {
			while (result.next()) {
				if (result.getInt("ID") == ID) {
					Boolean state = result.getBoolean("Active");
					result.updateBoolean("Active", !state);
					result.updateRow();
					if (!state) {
						btnTglActive.setText("deactivate");
					} else {
						btnTglActive.setText("activate");
					}
					break;
				}
			}
		} catch (SQLException ex) {
			Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_btnTglActiveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnTglActive;
    private javax.swing.JLabel lblAttack;
    private javax.swing.JLabel lblAttackVal;
    private javax.swing.JLabel lblCharname;
    private javax.swing.JLabel lblDefense;
    private javax.swing.JLabel lblDefenseVal;
    private javax.swing.JLabel lblRealname;
    private javax.swing.JPanel pnlTileHead;
    private javax.swing.JPanel pnlTileInfo;
    // End of variables declaration//GEN-END:variables
}

